---
name: Epic
description: A collection of related tickets.
labels:
  - epic
body:
  - type: markdown
    attributes:
      value: |
        This form is intended for grouping and collecting together related tickets to better gauge the scope of a problem/feature.

        If you are attempting to report a bug, propose a new feature, or some other code change please use one of the other forms available.

        > [!NOTE]
        > Epics that are incomplete or missing information may be closed as inactionable.

        Since there are already a lot of open issues, please also take a moment to search existing ones to see if a similar epic has already been opened. If you find something related, please upvote that issue and provide additional details as necessary.

        ðŸ’ Thank you for helping to make Conda better. We would be unable to improve Conda without our community!
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all of the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I searched open issues and couldn't find a duplicate
          required: true

  - type: textarea
    id: what
    attributes:
      label: What?
      description: >-
        What feature or problem will be addressed in this epic?
      placeholder: "Please describe here."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: >-
        Why is the reported issue(s) a problem, or why is the proposed feature needed?
        (Research and spike issues can be linked here.)
      value: |
        Please describe here and/or link to relevant supporting issues.
        - [ ] <supporting issue from user, research, or spike>
    validations:
      required: true

  - type: textarea
    id: user_impact
    attributes:
      label: User impact
      description: >-
        In what specific way(s) will users benefit from this change? (e.g. use cases or performance improvements)
      placeholder: "Please describe here."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: >-
        At what point can we close this epic as "completed"?
      value: |
        - [ ] <acceptance criterion>
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: >-
        What needs to be done to implement this change?
      value: |
        - [ ] <task or PR>
    validations:
      required: false

  - type: textarea
    id: linked_epics_issues
    attributes:
      label: Linked epics and issues
      description: >-
        Epics and issues that block or are blocked by this epic.
      value: |
        ### This epic is blocked by
        - [ ] <dependency epic or issue>

        ### This epic blocks
        - [ ] <dependency epic or issue>
    validations:
      required: false
