# edit this in [[ source.html_url ]]

name: Check authors

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - name: Check Authors
        uses: conda/actions/prepare-authors@ade1a3a5e5b7d3d124a03bf5d8c841645fb92a37 # v26.9.4
        with:
          mode: check
          since: tag
