# edit this in [[ source.html_url ]]

name: Check authors

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - name: Check Authors
        uses: conda/actions/prepare-authors@c8ad4261cc1d49709cb774289c68e63663bdc9d5 # v26.9.5
        with:
          mode: check
          since: tag
