# edit this in [[ source.html_url ]]

name: Check news

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  check-news:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check News
        uses: conda/actions/check-news@c1c846fb069313a5850f8bdda8be79e434ccc49f
        with:
          skip-label: no-news
          require-pr-number: true
          news-directory: news
