# edit this in [[ source.html_url ]]

version: 2
updates:
  [% if github_actions | default(true) %]
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    groups:
      workflows:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  [% endif %]
  [% if pre_commit | default(false) %]
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit:
        patterns:
          - '*'
  [% endif %]
  [% if pip | default(false) %]
  - package-ecosystem: pip
    directory: /docs/
    schedule:
      interval: monthly
    groups:
      docs:
        patterns:
          - '*'
  [% elif conda | default(false) %]
  - package-ecosystem: conda
    directory: /docs/
    schedule:
      interval: monthly
    groups:
      docs:
        patterns:
          - '*'
  [% endif %]
