name: tf-import
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  curate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          terraform_version: 1.3.7
      - name: Init
        run: |
          make init
      - name: Import
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_RO }}
        run: |
          make import-repositories
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4
        with:
          title: Terraform settings import from run ${{ github.run_id }}
          branch-suffix: random
          add-paths: '*.tf'
